version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
hooks:
  BeforeInstall:
    - location: stop_apache.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_apache.sh
      timeout: 300
      runas: ec2-user
